#!/usr/bin/env bash
# author: sundar.gnanasekaran@intel.com

export AIC_WORK_DIR=${PWD}

#Install Feature set packages / modules
./pre-requisites/setup-feature

#Initiate Early-Launch
#./pre-requisites/launch-early
./pre-requisites/cic-service

#Remove un-used apks
./pre-requisites/remove-app

#Install CIC
cd $AIC_WORK_DIR
echo "Installing CIC -- START"
./aic install -u -e -d none
echo "Installing CIC -- DONE"

#Check env path
AIC_WORK_DIR_PATH=$AIC_WORK_DIR/workdir
a=`grep -rn AIC_WORK_DIR /etc/environment`
if [ -z "$a" ]; then
	echo "export AIC_WORK_DIR=$AIC_WORK_DIR_PATH" | sudo tee -a /etc/environment
else
	sudo sed -i "s|export AIC_WORK_DIR.*||g" /etc/environment
	echo "export AIC_WORK_DIR=$AIC_WORK_DIR_PATH" | sudo tee -a /etc/environment
fi

a=`grep -rn AIC_WORK_DIR $HOME/.bashrc`
if [ -z "$a" ]; then
	echo "export AIC_WORK_DIR=$AIC_WORK_DIR_PATH" | sudo tee -a $HOME/.bashrc
else
	sudo sed -i "s|export AIC_WORK_DIR.*||g" $HOME/.bashrc
	echo "export AIC_WORK_DIR=$AIC_WORK_DIR_PATH" | sudo tee -a $HOME/.bashrc
fi

sudo chmod 777 -R $AIC_WORK_DIR_PATH

sudo systemctl enable cic

echo ""
echo "Reboot required for changes to be reflected !!"
read -p "Press Enter key to reboot: "
sudo reboot
