#!/bin/sh

sudo touch /lib/systemd/system/cic.service

echo "Adding CIC Service"
cat << EOF | sudo tee /lib/systemd/system/cic.service
[Unit]
Description="Start/Stop CIC service"
After=docker.service
BindsTo=docker.service
ReloadPropagatedFrom=docker.service

[Service]
WorkingDirectory=/AIC_WORK_DIR/
Type=notify
NotifyAccess=all
ExecStart=/bin/bash cic.sh start
ExecStop=/bin/bash cic.sh stop
RemainAfterExit=yes
TimeoutSec=15sec

[Install]
WantedBy=multi-user.target
EOF

sudo sed -i "s|/AIC_WORK_DIR|$AIC_WORK_DIR|g" /lib/systemd/system/cic.service
