#!/bin/sh

#
# This script is used to customize android by updating the update/Dockerfile before installing cic
# It has the following features:
#  1.Add new apps into system
#    a.For adding apps, just put the apk file under update/root/sytem/app/<app-name>/,no need any configure.
#  2.Remove apps, please configure APPS_TO_BE_REMOVED.
#  3.Remove files, please configure FILES_TO_BE_REMOVED.
#  4.Set system properties, please configure PROPERTIES.
#    a.For the properties need to be determined when installtion, please add additonal code. e.g. "For Timezone"
#
# Please edit the CUSTOMIZED CONTENT and run this script under the aic setup folder

############################CUSTOMIZED CONTENT###########################

#---------------------------
# 1.Remove apps
# Note: remove Settings will cause the device can't enter launcher ui issue
#---------------------------
#Edit APPS_TO_BE_REMOVED like the following:
#   APPS_TO_BE_REMOVED=\
#   "
#   /system/priv-app/DocumentsUI
#   /system/priv-app/MusicFX
#   "

#By default, nothing to be removed, keep it like this:
APPS_TO_BE_REMOVED=\
"
"

#---------------------------
# 2.Remove files
#---------------------------
#Edit FILES_TO_BE_REMOVED like the following:
#   FILES_TO_BE_REMOVED=\
#   "
#   /system/vendor/etc/permissions/android.hardware.bluetooth.xml
#   /system/vendor/etc/permissions/android.hardware.bluetooth_le.xml
#   "

#By default, nothing to be removed, keep it like this:
FILES_TO_BE_REMOVED=\
"
"

#---------------------------
# 3.Set properties
#---------------------------
#Edit PROPERTIES like the following:
#    PROPERTIES=\
#    "
#    persist.sys.locale=zh-Hans-CN
#    sys.display.size=1280x800
#    "

#By default, nothing to be set, keep it like this:
PROPERTIES=\
"
"

############################CUSTOMIZED CONTENT############################

function remove_files {
files=$1
if [ `echo $files | sed 's/ //g'` ]
then
    #do nothing
    :
else
   #echo "nothing to be removed"
   return
fi

#Add the head
echo 'RUN ["/system/bin/sh", "-c","\' >> update/Dockerfile

#Add the content
for file in $files
do
    echo "rm -rf $file && \\" >> update/Dockerfile
done

#Add the tail
echo "echo\"]" >> update/Dockerfile

}

function set_properties {
properties=$1
if [ `echo $properties | sed 's/ //g'` ]
then
    #do nothing
    :
else
   #echo "nothing to be set"
   return
fi

#Add the head
echo 'RUN ["/system/bin/sh", "-c","\' >> update/Dockerfile

#Add the content
for p in $properties
do
    key=`echo $p | cut -d '=' -f 1`
    val=`echo $p | cut -d '=' -f 1`
#remove the old if existed
cat >> update/Dockerfile << EOF
sed -i \"s|$key=.*||g\" /system/build.prop && \\
EOF

#append the new
cat >> update/Dockerfile << EOF
echo \"$p\" | tee -a /system/build.prop && \\
EOF

done

#Add the tail
echo "echo\"]" >> update/Dockerfile

}

echo "===customize android -- START"

echo "---Update Doeckerfile for apps to be removed -- START"
echo -e "\n#remove apps" >> update/Dockerfile
remove_files "$APPS_TO_BE_REMOVED"
echo "---Update Doeckerfile for apps to be removed -- END"

echo "---Update Doeckerfile for files to be removed -- START"
echo -e "\n#remove files" >> update/Dockerfile
remove_files "$FILES_TO_BE_REMOVED"
echo "---Update Doeckerfile for files to be removed -- END"

echo "---Update Doeckerfile for properties -- START"
#Append the properities of installation time
#For Timezone
localtz=$(timedatectl status |grep "Time zone")
localtzarr=(${localtz// / })
shorttz=${localtzarr[2]}
PROPERTIES=$PROPERTIES" ""persist.sys.timezone=$shorttz"
#For Timezone end

echo -e "\n#set properties" >> update/Dockerfile
set_properties "$PROPERTIES"
echo "---Update Doeckerfile for properties -- END"

echo "===customize android -- END"

