#!/usr/bin/env bash
# author: joe.zheng

if [[ -n `which docker` ]]; then
  echo "already installed, skip"
  exit
fi

curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun
sudo usermod -aG docker $USER
