#!/bin/sh

a=`grep -ir "Alias=rc-local.service" /etc/systemd/system/rc-local.service`

if [ -z "$a" ] #if script run before -- START
then
echo "Adding launch-early"
sudo ln -fs /lib/systemd/system/rc-local.service /etc/systemd/system/rc-local.service
cat << EOF | sudo tee -a /etc/systemd/system/rc-local.service 
[Install]  
WantedBy=multi-user.target  
Alias=rc-local.service  
EOF
fi #if script run before -- END

sudo rm -f /etc/rc.local
sudo touch /etc/rc.local
cat << 'EOF' | sudo tee /etc/rc.local 
#!/bin/sh
# start aic
while (( $(ps -ef | grep -v grep | grep dockerd | wc -l) == 0 )); do sleep 1; done
/AIC_WORK_DIR/aic start
modprobe snd-dummy
exit 0
EOF
sudo chmod +x /etc/rc.local

sudo sed -i "s|/AIC_WORK_DIR|$AIC_WORK_DIR|g" /etc/rc.local

