#!/bin/sh

echo "Update Doeckerfile for remove apk -- START"

# Note: remove Settings will cause the device can't enter launcher ui issue
cd $AIC_WORK_DIR
mkdir -p update/root
#Add following content into update/Dockerfile
cat << EOF | sudo tee -a update/Dockerfile
RUN ["/system/bin/sh", "-c", "rm -rf /system/priv-app/Contacts"]
RUN ["/system/bin/sh", "-c", "rm -rf /system/vendor/etc/permissions/android.hardware.bluetooth.xml"]
RUN ["/system/bin/sh", "-c", "rm -rf /system/vendor/etc/permissions/android.hardware.bluetooth_le.xml"]
RUN ["/system/bin/sh", "-c", "rm -rf /system/priv-app/MusicFX"]
RUN ["/system/bin/sh", "-c", "rm -rf /system/priv-app/DocumentsUI"]
RUN ["/system/bin/sh", "-c", "rm -rf /system/app/Email"]
RUN ["/system/bin/sh", "-c", "rm -rf /system/app/Calendar"]
RUN ["/system/bin/sh", "-c", "rm -rf /system/app/Music"]
RUN ["/system/bin/sh", "-c", "rm -rf /system/app/ExactCalculator"]
RUN ["/system/bin/sh", "-c", "rm -rf /system/app/QuickSearchBox"] 
EOF

echo "Update Doeckerfile for remove apk -- END"
