#!/usr/bin/env bash
# author: sundar.gnanasekaran@intel.com

echo "Installing packages from feature/ -- START"
sudo dpkg -i $AIC_WORK_DIR/cfc/*.deb
echo "Installing packages from feature/ -- DONE"

#Grant permission for cfc.desktop
sudo chown $(whoami):$(whoami) /home/$(whoami)/Desktop/cfc.desktop
