#!/usr/bin/env bash
# author: sundar.gnanasekaran@intel.com

echo ""
echo "***********************************"
echo " Preparing for cic installation..."
echo "***********************************"
echo ""

function clean_cic {
    rm -rf /opt/cic
    rm -rf /etc/profile.d/create_pasocket.sh
    mkdir -p /opt/cic
}

function check_docker {
    if [ ! -x "$(command -v docker)" ]; then
        echo "[AIC] docker not installed, please install it first!"
        exit -1
    fi
}

function check_containers {
    if [ -z "$(docker ps -a | awk '{print $NF}' | grep -w aic-manager)" ]; then
        echo "[AIC] aic-manager container not existed, please re-install aic!"
        exit -1
    fi
    if [ -z "$(docker ps -a | awk '{print $NF}' | grep android)" ]; then
        echo "[AIC] android container not existed, please re-install aic!"
        exit -1
    fi
}

function detect_work_dir {
    if [ -z "$AIC_WORK_DIR" ]; then
        echo "AIC_WORK_DIR is not set!"
        exit -1
    fi
}

## Clean previous installed cic
clean_cic

if [ -z "$AIC_WORK_DIR" ]; then
    echo "AIC_WORK_DIR is not set, try to detect it!"
    check_docker
#    check_containers
    AIC_WORK_DIR=$(docker inspect aic-manager | grep /ipc:/ipc | sed  's/[\",\,, ]//g' | sed 's/\/ipc:\/ipc//')
    export AIC_WORK_DIR=$AIC_WORK_DIR

    # append to the .bashrc
    sed -i '/AIC_WORK_DIR/d' /etc/environment
    echo "export AIC_WORK_DIR=$AIC_WORK_DIR" >> /etc/environment
fi
